### ISSUE TITLE
Terminology Discussion 

### ISSUE THREAD

**Issue by sjsakib** [javascript-tutorial/bn.javascript.info#5]

**Comment by sjsakib** [comment]
`error message` কে ‍`ভুল বার্তা` করলে ভাল নাকি যা আছে তা রাখলে ভাল হবে?

**Comment by jamal-pb95** [comment]
_এরর মেসেজ_ লিখেন। টেকনিক্যাল কথা সহজে বুঝা যাবে।

**Comment by jamal-pb95** [comment]
added to our [glossary list](https://github.com/javascript-tutorial/bn.javascript.info/wiki/Glossary).
